version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: central_empresa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: pass
      DB_NAME: central_empresa
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  db_data:
